apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: net-secret-read    
  name: net-secret-read  
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-secret-read      
  template:
    metadata:
      labels:
        app: net-secret-read        
    spec:     
      containers:
      - name : net-secret-read      
        image: ceibatrainer/test-secret-core
        imagePullPolicy: "Always"
        env: 
        - name: "db_host"
          value: "mysql_server.default"
        - name: "db_name"
          value: "company"
        - name: "db_user"
          value: "root"
        - name: "db_pass"
          value: "toor"    
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: my-secret                             
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
