apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-for-netcore    
  name: mysql-for-netcore  
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-for-netcore      
  template:
    metadata:
      labels:
        app: mysql-for-netcore        
    spec:     
      containers:
      - name : mysql-for-netcore      
        image: ceibatrainer/mysqlseed
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3306
          protocol: TCP                           
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0